### ISSUE TITLE
Package Size

### ISSUE THREAD

**Issue by mansoor292** [amandeepmittal/react-animated-dots#7]
react-dom is hardcoded in your package.json

I cannot believe 2200 downloads a week for this one file

import styled, { keyframes } from 'styled-components';

const blink = keyframes`
  50% {color: transparent;}
`;
export const Dot = styled.span`
  animation: 1s ${blink} infinite;
  &:nth-child(1) {
    animation-delay: 0ms;
  }
  &:nth-child(2) {
    animation-delay: 250ms;
  }
  &:nth-child(3) {
    animation-delay: 500ms;
  }
`;

**Comment by amandeepmittal** [comment]
Hey! Apologies for not getting back to you.

Yeah, I do not believe myself either that people are still downloading this package 😄
